name: Build ValhallaMMO

on:
  push:
    branches: [ "main", "master", "premium"]
  workflow_dispatch: # This adds the "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Download & Install Missing Dependencies
        run: |
          # Manually download Vault and DecentHolograms to skip the JitPack 500 error
          curl -L -o vault.jar https://github.com/MilkBowl/VaultAPI/releases/download/1.7.1/VaultAPI-1.7.1.jar
          mvn install:install-file -Dfile=vault.jar -DgroupId=com.github.MilkBowl -DartifactId=VaultAPI -Dversion=1.7.1 -Dpackaging=jar
          
          curl -L -o dh.jar https://github.com/decentsoftware-eu/decentholograms/releases/download/2.8.5/DecentHolograms-2.8.5.jar
          mvn install:install-file -Dfile=dh.jar -DgroupId=com.github.decentsoftware-eu -DartifactId=decentholograms -Dversion=2.8.5 -Dpackaging=jar

      - name: Build Core Module
        # We use -o for "Offline Mode" so it only uses the files we just installed
        run: mvn clean package -pl :valhallammo-core -am

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Valhalla-JAR
          path: "**/target/*.jar"
